# Generated by Django 4.1.3 on 2022-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productdetails_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='in_stock_total',
            field=models.BooleanField(default=True),
        ),
    ]
