# Generated by Django 4.1.3 on 2022-12-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='alex', max_length=50, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='alex', max_length=50, verbose_name='last name'),
            preserve_default=False,
        ),
    ]
