# Generated by Django 4.1.3 on 2023-01-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('none', 'none')], default='none', max_length=10),
        ),
    ]
