# Generated by Django 4.1.3 on 2023-01-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
    ]
