# Generated by Django 4.1.3 on 2022-12-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_categories_url_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
