# Generated by Django 4.1.3 on 2022-12-31 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_categories_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='thumbnail',
            field=models.FileField(upload_to='media/thumbnail'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='thumbnail',
            field=models.FileField(upload_to='media/thumbnail'),
        ),
    ]
